### ISSUE TITLE
Update needed

### ISSUE THREAD

**Issue by Git-GT** [deveth0/NetbeansRegexPlugin#2]
Hi, could you update for Netbeans 8.2 please?

**Comment by deveth0** [comment]
hey, thanks for the feedback. I didn't find time yet but you can install the plugin manually, it works fine with 8.2 :)

**Comment by deveth0** [comment]
Here we go... 
http://plugins.netbeans.org/plugin/63405

**Comment by Git-GT** [comment]
Hi deveth, thanks a lot!
