### ISSUE TITLE
Style changes?

### ISSUE THREAD

**Issue by Chris2011** [deveth0/NetbeansRegexPlugin#3]
I used your plugin and it is very nice, but I use this page: https://regex101.com/ It would be nice to adapt the design from it, The thing is the focus is most on the part where you have the regex input and the text, which will be tested. The regex could be colorized (is an option) and the text to test, shows you what the regex will match. The other information is on the right, which is good, because they have not that focus as the input/output fields. It would be nice to adapt most of the style from the page and I don't need any other regex tools anymore.

Regards

Chris

**Comment by deveth0** [comment]
Hey,
yeah, design is not fully optimal but keep in mind that the plugin has to work with very limited space (e.g. if it's kept in the lower navigation). 

Feel free to for the project and create a pullrequests with updates :)

**Comment by Chris2011** [comment]
The limited space I think is not really the problem, you already use the Editor pane where you can have enough space and if someone will use it, they can hide the panels, if they don't want it. But yes, If I have time, I can do so.

**Comment by Chris2011** [comment]
Because of lack of time, I will not find time to do any improvements here :(
